# Generated by Django 2.2.6 on 2019-10-15 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Value_Investing_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Financial_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Information Date')),
                ('is_ttm', models.BooleanField(verbose_name='Is TTM Info')),
                ('total_revenue', models.FloatField(verbose_name='Total Revenue')),
                ('net_income', models.FloatField(verbose_name='Net Income')),
                ('total_assets', models.FloatField(verbose_name='Total Assets')),
                ('total_liabilities', models.FloatField(verbose_name='Total Liabilities')),
                ('long_term_debt', models.FloatField(verbose_name='Long Term Debt')),
                ('dividend_rate', models.FloatField(verbose_name='Dividend Rate')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Value_Investing_App.Stock')),
            ],
        ),
    ]
