# Generated by Django 2.2.6 on 2019-10-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Value_Investing_App', '0002_auto_20191014_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_info',
            name='dividend_rate',
            field=models.FloatField(default=0, verbose_name='Dividend Rate'),
        ),
        migrations.AlterField(
            model_name='financial_info',
            name='is_ttm',
            field=models.BooleanField(default=False, verbose_name='Is TTM Info'),
        ),
        migrations.AlterField(
            model_name='financial_info',
            name='long_term_debt',
            field=models.FloatField(blank=True, null=True, verbose_name='Long Term Debt'),
        ),
        migrations.AlterField(
            model_name='financial_info',
            name='net_income',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Income'),
        ),
        migrations.AlterField(
            model_name='financial_info',
            name='total_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Assets'),
        ),
        migrations.AlterField(
            model_name='financial_info',
            name='total_liabilities',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Liabilities'),
        ),
        migrations.AlterField(
            model_name='financial_info',
            name='total_revenue',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Revenue'),
        ),
    ]
