# Generated by Django 2.2.6 on 2019-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Value_Investing_App', '0003_auto_20191015_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_info',
            name='ammount_of_shares',
            field=models.IntegerField(default=0, verbose_name='Ammount of Shares'),
        ),
    ]
